dist: xenial   # required for Python >= 3.7
language: python
matrix:
  include:
    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: choco install python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover -v