dist: xenial   # required for Python >= 3.7
services:
  - xvfb
language: python
matrix:
  include:
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: choco install python --version 3.8.0
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
python:
  - "3.8"
install:
  - python -m pip install -r requirements.txt
script:
  - python -m unittest discover -v